package LSAApp;


/**
* LSAApp/LSAHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LSA.idl
* Thursday, December 4, 2014 7:47:23 PM EST
*/

abstract public class LSAHelper
{
  private static String  _id = "IDL:LSAApp/LSA:1.0";

  public static void insert (org.omg.CORBA.Any a, LSAApp.LSA that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LSAApp.LSA extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (LSAApp.LSAHelper.id (), "LSA");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LSAApp.LSA read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LSAStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LSAApp.LSA value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static LSAApp.LSA narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LSAApp.LSA)
      return (LSAApp.LSA)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LSAApp._LSAStub stub = new LSAApp._LSAStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static LSAApp.LSA unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LSAApp.LSA)
      return (LSAApp.LSA)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LSAApp._LSAStub stub = new LSAApp._LSAStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
