package LSAApp;

import java.io.IOException;

import org.omg.CORBA.ORBPackage.InvalidName;
import org.omg.CosNaming.NamingContextPackage.CannotProceed;
import org.omg.CosNaming.NamingContextPackage.NotFound;


/**
* LSAApp/LSAOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LSA.idl
* Thursday, December 4, 2014 7:47:23 PM EST
*/

public interface LSAOperations 
{
  boolean findFile (String fileName) throws IOException, InvalidName, NotFound, CannotProceed, org.omg.CosNaming.NamingContextPackage.InvalidName;
  boolean hasFile (String fileName);
  void storeFile (String fileName) throws IOException;
  void contactServer (int i) throws InvalidName, NotFound, CannotProceed, org.omg.CosNaming.NamingContextPackage.InvalidName, IOException;
  String getRecord (int recordNum) throws IOException;
  String sendFile (String fileName) throws IOException;
} // interface LSAOperations
