package LSAApp;

import java.io.IOException;

import org.omg.CORBA.ORBPackage.InvalidName;
import org.omg.CosNaming.NamingContextPackage.CannotProceed;
import org.omg.CosNaming.NamingContextPackage.NotFound;


/**
* LSAApp/LSAPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LSA.idl
* Thursday, December 4, 2014 7:47:23 PM EST
*/

public abstract class LSAPOA extends org.omg.PortableServer.Servant
 implements LSAApp.LSAOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("findFile", new java.lang.Integer (0));
    _methods.put ("hasFile", new java.lang.Integer (1));
    _methods.put ("storeFile", new java.lang.Integer (2));
    _methods.put ("contactServer", new java.lang.Integer (3));
    _methods.put ("getRecord", new java.lang.Integer (4));
    _methods.put ("sendFile", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // LSAApp/LSA/findFile
       {
         String fileName = in.read_string ();
         boolean $result = false;
         try {
			$result = this.findFile (fileName);
		} catch (InvalidName | NotFound | CannotProceed
				| org.omg.CosNaming.NamingContextPackage.InvalidName
				| IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // LSAApp/LSA/hasFile
       {
         String fileName = in.read_string ();
         boolean $result = false;
         $result = this.hasFile (fileName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // LSAApp/LSA/storeFile
       {
         String fileName = in.read_string ();
         try {
			this.storeFile (fileName);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
         out = $rh.createReply();
         break;
       }

       case 3:  // LSAApp/LSA/contactServer
       {
         int i = in.read_long ();
         try {
			this.contactServer (i);
		} catch (InvalidName | NotFound | CannotProceed
				| org.omg.CosNaming.NamingContextPackage.InvalidName
				| IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
         out = $rh.createReply();
         break;
       }

       case 4:  // LSAApp/LSA/getRecord
       {
         int recordNum = in.read_long ();
         String $result = null;
         try {
			$result = this.getRecord (recordNum);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // LSAApp/LSA/sendFile
       {
         String fileName = in.read_string ();
         String $result = null;
         try {
			$result = this.sendFile (fileName);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:LSAApp/LSA:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public LSA _this() 
  {
    return LSAHelper.narrow(
    super._this_object());
  }

  public LSA _this(org.omg.CORBA.ORB orb) 
  {
    return LSAHelper.narrow(
    super._this_object(orb));
  }


} // class LSAPOA
