package LSAApp;


/**
* LSAApp/LSA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LSA.idl
* Thursday, December 4, 2014 7:47:23 PM EST
*/

public interface LSA extends LSAOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LSA
