package LSAApp;

/**
* LSAApp/LSAHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LSA.idl
* Thursday, December 4, 2014 7:47:23 PM EST
*/

public final class LSAHolder implements org.omg.CORBA.portable.Streamable
{
  public LSAApp.LSA value = null;

  public LSAHolder ()
  {
  }

  public LSAHolder (LSAApp.LSA initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LSAApp.LSAHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LSAApp.LSAHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LSAApp.LSAHelper.type ();
  }

}
